django_social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include("pwitter.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pwitter/urls.py
import allauth.account.views
from django.urls import path
from .views import profile_list, DashboardView, ProfileDetail
from . import views


app_name = "pwitter"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path('profile_list/', profile_list, name="profile_list"),
    path('profile/<int:pk>', ProfileDetail.as_view(), name="profile"),
    path('accounts/logout/', allauth.account.views.LogoutView.as_view(), name='sign-out'),
    path('delete/<int:pk>', views.pweet_delete, name='pweet_delete'),
    path('/<int:pk>', views.like_view, name='like_pweet'),
    path('/reply/<int:pk>', views.reply_like_view, name='like_reply'),
    path('register', views.register_request, name='register'),
]

pwitter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Pweet, Profile, PweetReply
from django.contrib.auth.models import User

class PweetReplyForm(forms.ModelForm):
    reply_body = forms.CharField(required=True,
                           widget=forms.widgets.Textarea(
                               attrs={
                                   "placeholder": "Reply...",
                                   "class": "textarea is-success is-small",
                               }
                           ),
                           label="",
                           )

    class Meta:
        model = PweetReply
        exclude = ('user', 'created_at', 'likes')


class ChangeProfilepicForm(forms.ModelForm):
    user_image = forms.FileField()

    class Meta:
        model = Profile
        fields = ('user_image',)


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class PweetForm(forms.ModelForm):
    body = forms.CharField(required=True,
                           widget=forms.widgets.Textarea(
                               attrs={
                                   "placeholder": "Pweet something...",
                                   "class": "textarea is-success is-medium",
                               }
                           ),
                           label="",
                           )

    class Meta:
        model = Pweet
        exclude = ("user", "picture", "likes")

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <title>Pwitter</title>
</head>
<body>
<a href="{% url 'pwitter:dashboard' %}">
<section class="hero is-small is-success mb-4">
            <div class="hero-body">
                <div class="columns">
                    <div class="column">
                    <h1 class="title is-1">Pwitter</h1>
                    <p class="subtitle is-4">Your tiny social network built with Django</p>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="column">
                    <div class="box is-pulled-right">
                    <article class="media">
                    <figure class="media-left">
                    {% if user.profile.user_image %}
                    <p class="image is-64x64">
                        <img src="{{ MEDIA_URL }}{{ user.profile.user_image.name }}">
                    </p>
                    {% endif %}
                    </figure>
                    <div class="media-content">
                    <div class="content">
                        <strong>Logged as:</strong>
                        <br>
                        <a href="{% url 'pwitter:profile' user.profile.pk %}">
                        <strong class="has-text-black">{{ user.profile.user }}</strong>
                        </a>
                    {% endif %}
                    </div>
                    </div>
                    </article>
                    </div>
                    </div>
                    </div>


    </div>

</section>
</a>
    <div class="container">
    <div class="columns">
        {% block content %}

        {% endblock content %}
    </div>
    </div>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="column">
        {% for followed in user.profile.follows.all %}
            {% for pweet in followed.user.pweets.all %}
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-64x64">
                                {% if followed.user_image %}
                                <img src="{{MEDIA_URL}}{{ followed.user_image.name }}" alt="profile_image">
                                {% else %}
                                <img src="https://bulma.io/images/placeholders/96x96.png"
                                 alt="Placeholder image">
                                {% endif %}
                            </figure>
                        </div>
                        <div class="media-content">

                            <div class="content">
                            <div class="columns">
                                <div class="column">
                                    <p>
                                    <strong><a href="{% url 'pwitter:profile' pweet.user.id %}">{{ pweet.user.username }}</a></strong>
                                    <small>@{{ pweet.user.username }}</small>
                                    <small>{{ pweet.created_at }}</small>
                                    <br>
                                    {{ pweet.body }}
                                    {% if pweet.pweet_image %}
                                    <div class="container">
                                    <img src="{{ MEDIA_URL }}{{ pweet.pweet_image.name }}">
                                    </div>
                                    {% endif %}
                                </p>
                                </div>
                                {% if user.username == pweet.user.username %}
                                <form action="{% url 'pwitter:pweet_delete' pweet.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="button is-right">
                                        <span class="icon is-small">
                                            <i class="fas fa-trash"></i>
                                        </span>
                                    </button>
                                </form>
                                {% endif %}
                            </div>

                            </div>
                            <nav class="level is-mobile">
                                <div class="level-left">
                                    <a class="level-item" aria-label="reply">
                                        <span class="icon is-small">
                                            <i class="fas fa-reply" aria-hidden="true"></i>
                                        </span>
                                    </a>
{#                                    <a class="level-item" aria-label="retweet">#}
{#                                        <span class="icon is-small">#}
{#                                            <i class="fas fa-retweet" aria-hidden="true"></i>#}
{#                                        </span>#}
{#                                    </a>#}
                                    <a class="level-item" aria-label="like">
                                        <form action="{% url 'pwitter:like_pweet' pweet.id %}" method="post">
                                    {% csrf_token %}
                                    <button  type="submit" class="button is-right" name="pweet_id"
                                             value="{{ pweet.id }}">
                                        <span class="icon is-small">
                                            <i class="fas fa-solid fa-heart" aria-hidden="true"></i>
                                        </span>
                                        <p>{{ pweet.likes.count }}</p>
                                    </button>
                                        </form>
                                    </a>
                                </div>
                            </nav>
                            <form method="post">
                                        {{ reply_form.as_p }}
                                        {% csrf_token %}
{#                                        <input class="input is-info" name="reply_body" maxlength="140" required="" id="id_reply_body" placeholder="Type your reply...">#}
                                        <input class="btn btn-primary" type="submit">
                                        </form>


                            {% for reply in pweet.replies.all %}
                                <article class="media">
                                <figure class="media-left">
                                    <p class="image is-48x48">
                                        {% if reply.user.profile.user_image %}
                                        <img src="{{MEDIA_URL}}{{ reply.user.profile.user_image.name}}" alt="reply_profile_image">
                                        {% else %}
                                        <img src="https://bulma.io/images/placeholders/96x96.png"
                                        alt="Placeholder image">
                                        {% endif %}
                                    </p>
                                </figure>
                                <div class="media-content">
                                    <div class="content">
                                        <p>
                                            <strong><a href="{% url 'pwitter:profile' reply.user.id %}">{{ reply.user.username }}</a></strong>
                                            <small>@{{ reply.user.username }}</small>
                                            <small>{{ reply.created_at }}</small>

                                            <br>
                                            {{ reply.reply_body }}
                                            <form action="{% url 'pwitter:like_reply' reply.pk%}" method="post">
                                            {% csrf_token %}
                                            <button  type="submit" class="button is-right" name="reply_pk"
                                             value="{{ reply.pk }}">
                                            <span class="icon is-small">
                                            <i class="fas fa-solid fa-heart" aria-hidden="true"></i>
                                            </span>
                                            <p>{{ reply.likes.count }}</p>
                                            </button>
                                            </form>
                                        </p>

                                    </div>
                                </div>
                                </article>
                            {% endfor %}
                        </div>
                    </article>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
    <div class="column is-one-third">
    <div class="block">
        <a href="{% url 'pwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:profile' request.user.profile.pk %}">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:sign-out' %}">
            <button class="button is-danger is-light is-outlined is-fullwidth">
                Logout
            </button>
        </a>
    </div>
    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a Pweet</h2>
        </div>
        <div class="block">
    <form name="pweet_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ pweet_form }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Pweet
        </button>
    </form>
        </div>
    </div>
    </div>
{% endblock content %}

templates/form.html
{% block content %}
    <div class="field">
    <label class="label">Add a Pweet</label>
    <div class="control">
        <textarea class="textarea is-large is-focused" placeholder="Pweet something..."></textarea>
    </div>
    </div>
    <div class="columns">
    <div class="column">
    <div class="file is-boxed">
    <label class="file-label">
        <input class="file-input" type="file" name="image">
        <span class="file-cta">
            <span class="file-icon">
                <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
                Choose an image...
            </span>
        </span>
    </label>
    </div>
    </div>
    <div class="column">
        <input class="button is-primary is-fullwidth is-large" type="submit" value="Pweet">
    </div>
    </div>


{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="column">
        <div class="block">
        <h1 class="title is-1">
            {{ profile.user.username|upper }}'s Pweets
        </h1>

    <form method="post">
    {% csrf_token %}
    <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
        <button class="button is-success is-static">Follow</button>
        <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
        {% else %}
        <button class="button is-success" name="follow" value="follow" >Follow</button>
        <button class="button is-danger is-static">Unfollow</button>
        {% endif %}
    </div>
    </form>
    <div class="content">
        {% for pweet in profile.user.pweets.all %}
        <div class="box">
        {{ pweet.body }}
        <span class="is-small has-text-grey-light">
            {{ pweet.created_at }}
        </span>
        </div>
        {% endfor %}
        {% for pweet_reply in profile.user.pweets_reply.all %}
        <div class="box">
        {{ pweet_reply.reply_body }}
        <span class="is-small has-text-grey-light">
            {{ pweet_reply.created_at }}
        </span>
        </div>
        {% endfor %}
    </div>
    {% if profile.user.username == user.username %}
    <form method="post" enctype="multipart/form-data">>
        {% csrf_token %}
        {{ change_profile_pic_form }}
        <button name="change_profile_pic_form" type="submit">Submit</button>
    </form>
    {% endif %}
    </div>
    </div>
    <div class="column is-one-third">
    <div class="block">
        <a href="{% url 'pwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:profile' request.user.profile.pk %}">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:sign-out' %}">
            <button class="button is-danger is-light is-outlined is-fullwidth">
                Logout
            </button>
        </a>
    </div>
    <div class="block">
    <h3 class="title is-4">
        {{ profile.user.username }} follows:
    </h3>
    <div class="content">
        <ul>
            {% for following in profile.follows.all %}

                <li>
                <a href="{% url 'pwitter:profile' following.pk %}">
                    {{ following }}
                </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    </div>
    <div class="block">
    <h3 class="title is-4">
        {{ profile.user.userame }} is followed by:
    </h3>
    <div class="content">
        <ul>
            {% for follower in profile.followed_by.all %}
            <li>
                <a href="{% url 'pwitter:profile' follower.pk %}">
                    {{ follower }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    </div>
    </div>

{% endblock content %}

templates/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="column">
    {% for profile in profiles %}
    <div class="block">
    <div class="card">
        <a href="{% url 'pwitter:profile' profile.pk%}">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            {% if profile.user_image %}
                            <img src="{{MEDIA_URL}}{{ profile.user_image.name }}" alt="profile_image">
                            {% else %}
                            <img src="https://bulma.io/images/placeholders/96x96.png"
                                 alt="Placeholder image">
                            {% endif %}
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">
                            {{ profile.user.username }}
                        </p>
                        <p class="subtitle is-6">
                            @{{ profile.user.username|lower }}
                        </p>
                    </div>



                </div>
            </div>
        </a>
    </div>

    </div>
{% endfor %}
</div>
    <div class="column is-one-third">
<div class="block">
        <a href="{% url 'pwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:profile' request.user.profile.pk %}">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <div class="block">
        <a href="{% url 'pwitter:sign-out' %}">
            <button class="button is-danger is-light is-outlined is-fullwidth">
                Logout
            </button>
        </a>
    </div>
</div>




{% endblock content %}